### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ecyht2** [mmwillet/TTS.cpp#1]
Any plans to support Linux? I did manage to get it compiled by changing the code. Might be able to contribute after some testing. 
PS: I also uploaded the pre-converted GGUF files to [huggingface](https://huggingface.co/ecyht2/parler-tts-mini-v0.1-GGUF).

**Comment by mmwillet** [comment]
@ecyht2 I am currently traveling so I won't make substantial updates in the next couple days. However, I do plan to support linux and windows (it is just currently easier for me to test on OS X while I still develop core functionality). Much shouldn't need to change in order to support both, so if you have working changes please feel free to PR them.

Separately, thanks for uploading the GGUF files to huggingface! I plan to change the GGUF format a little in the coming weeks to bring it in line with the standardization which llama.cpp uses, so I may ask you to change the hugging face model when I do. Additionally, I should note that in order to avoid initially supporting the Parler text encoder (which is a separate T5Encoder model) on the GGML side and in order to reduce load time, disk footprint, and memory footprint, the GGUF file stores a pre-encoded prompt for conditional generation. This means that for unique conditional generation (i.e. generation with cross attention), a new GGUF file will still have to be compiled.

I'll prioritize adding support for the T5 encoder (llama.cpp already supports the structure actually) and formalizing the GGUF format when I get back.
